export function renderSettingsPage(publicUrl: string): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>pi GitHub Bot</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#17202a;background:#f6f7f9}body{max-width:920px;margin:0 auto;padding:40px 20px}main{background:#fff;border:1px solid #dfe3e8;border-radius:8px;padding:28px;box-shadow:0 8px 30px #17202a0d}h1{margin:0 0 8px;font-size:28px}p{color:#59636e}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:24px}label{display:flex;gap:10px;align-items:center;padding:14px;border:1px solid #e2e6ea;border-radius:6px}input[type=text]{width:100%;box-sizing:border-box;padding:10px;border:1px solid #c8ced6;border-radius:5px}.full{grid-column:1/-1}button{background:#1f6feb;color:#fff;border:0;border-radius:5px;padding:10px 16px;font-weight:600;cursor:pointer}code{background:#f0f2f5;padding:2px 5px;border-radius:4px}@media(max-width:640px){.grid{grid-template-columns:1fr}}
</style></head><body><main><h1>pi GitHub Bot</h1><p>Self-hosted GitHub App control panel. Public webhook URL: <code>${escapeHtml(publicUrl)}/webhooks/github</code></p>
<form id="settings"><div class="grid"><label class="full">Admin token<input id="token" type="password" autocomplete="off" required></label><label>Owner<input id="owner" type="text" required></label><label>Repository<input id="repo" type="text" required></label>
<label><input id="mention" type="checkbox" checked> Respond to @mentions</label><label><input id="triage" type="checkbox"> Triage new issues</label><label><input id="labels" type="checkbox"> Apply issue labels</label><label><input id="review" type="checkbox"> Review new PRs</label><label><input id="draft" type="checkbox"> Review draft PRs</label><label><input id="forks" type="checkbox"> Review fork PRs</label><label><input id="write" type="checkbox"> Allow agent writes</label><div class="full"><button type="submit">Save repository settings</button> <span id="status"></span></div></div></form></main>
<script>
const $=id=>document.getElementById(id); function checked(id){return $(id).checked} function set(id,v){$(id).checked=Boolean(v)}
$('settings').addEventListener('submit',async e=>{e.preventDefault();$('status').textContent='Saving…';const s={enabled:true,mention:{enabled:checked('mention')},issueTriage:{enabled:checked('triage'),autoLabels:checked('labels')},pullRequestReview:{enabled:checked('review'),skipDraft:!checked('draft'),skipForks:!checked('forks')},agent:{allowWrite:checked('write')}};const r=await fetch('/api/settings/'+encodeURIComponent($('owner').value)+'/'+encodeURIComponent($('repo').value),{method:'PUT',headers:{'content-type':'application/json','authorization':'Bearer '+$('token').value},body:JSON.stringify(s)});$('status').textContent=r.ok?'Saved.':await r.text()})
</script></body></html>`;
}
function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character] ?? character); }
